module.exports = {
  "architect": "Architect",
  "art_director": "Art Director",
  "backend": "Backend Developer",
  "frontend": "Frontend Developer",
  "full_stack": "Full-Stack Developer",
  "pm": "Project Manager",
  "qa_tester": "QA Tester",
  "sys_admin": "System Administrator",
  "ux_designer": "UX Designer",
  "visual_designer": "Visual Designer",
  "api": "APIs",
  "adobe_creative_suite": "Adobe Creative Suite",
  "bootstrap": "Bootstrap",
  "cli": "CLI",
  "communication": "Communication",
  "custom_themes": "Custom Themes",
  "ecommerce": "eCommerce",
  "gitflow": "Git-flow",
  "github": "GitHub",
  "jquery": "jQuery",
  "lamp": "LAMP Stack",
  "mysql": "MariaDB / MySQL",
  "mobile_design": "Mobile Design",
  "sass": "SASS",
  "seo": "SEO",
  "ui": "UI / UX",
  "wix": "Wix",
  "squarespace": "Squarespace",
  "shopify": "Shopify",
  "php": "PHP",
  "html": "HTML",
  "css": "CSS",
  "javascript": "JavaScript",
  "dotnet": "DotNet",
  "java": "Java",
  "ruby": "Ruby",
  "drupal": "Drupal",
  "wordpress": "WordPress",
  "sitecore": "Sitecore",
  "aem": "Adobe Experience Manager (AEM)",
  "laravel": "Laravel",
  "ror": "Ruby on Rails (RoR)",
  "episerver": "Episerver",
  "hours_10": "10 hours per week",
  "hours_20": "20 hours per week",
  "hours_30": "30 hours per week",
  "hours_40": "40 hours",
  "open": "As needed, Open to offers",
  "citizen": "I am a citizen",
  "not_citizen": "I am in need of sponsorship",
  "elementary": "Elementary",
  "intermediate": "Intermediate",
  "native": "Native",
  "proficient": "Proficient",
  "drupal_profile": "Drupal Profile",
  "wp_profile": "WP Profile",
  "entry": "Entry Level",
  "intermediate": "Intermediate",
  "expert": "Expert/Advanced",
  "contract": "Contract",
  "contract_to_perm": "Contract-to-Perm",
  "permanent": "Permanent",
  "n_a": "N/A",
  "remote": "Remote",
  "on_site": "On-site",
  "mixed": "Mixed",
}
