export default {
  architect: 'Architect',
  art_director: 'Art Director',
  backend: 'Back-end Developer',
  frontend: 'Front-end Developer',
  full_stack: 'Full-Stack Developer',
  pm: 'Project Manager',
  qa_tester: 'QA Tester',
  sys_admin: 'System Administrator',
  ux_designer: 'UX Designer',
  visual_designer: 'Visual Designer',
  api: 'APIs',
  adobe_creative_suite: 'Adobe Creative Suite',
  bootstrap: 'Bootstrap',
  cli: 'CLI',
  communication: 'Communication',
  custom_themes: 'Custom Themes',
  ecommerce: 'eCommerce',
  gitflow: 'Git-flow',
  github: 'GitHub',
  jquery: 'jQuery',
  lamp: 'LAMP Stack',
  mysql: 'MariaDB / MySQL',
  mobile_design: 'Mobile Design',
  sass: 'SASS',
  seo: 'SEO',
  ui: 'UI / UX',
  wix: 'Wix',
  squarespace: 'Squarespace',
  shopify: 'Shopify',
  php: 'PHP',
  html: 'HTML',
  css: 'CSS',
  javascript: 'JavaScript',
  dotnet: 'DotNet',
  java: 'Java',
  ruby: 'Ruby',
  drupal: 'Drupal',
  wordpress: 'WordPress',
  sitecore: 'Sitecore',
  aem: 'Adobe Experience Manager (AEM)',
  laravel: 'Laravel',
  ror: 'Ruby on Rails (RoR)',
  episerver: 'Episerver',
  hours_10: '10 hours per week',
  hours_20: '20 hours per week',
  hours_30: '30 hours per week',
  hours_40: '40 hours',
  open: 'As needed, Open to offers',
  citizen: 'I am a citizen',
  not_citizen: 'I am in need of sponsorship',
  elementary: 'Elementary',
  intermediate: 'Intermediate',
  native: 'Native',
  proficient: 'Proficient',
  drupal_profile: 'Drupal Profile',
  wp_profile: 'WP Profile',
  entry: 'Entry Level',
  expert: 'Expert/Advanced',
  contract: 'Contract',
  contract_to_perm: 'Contract-to-Perm',
  permanent: 'Permanent',
  n_a: 'N/A',
  remote: 'Remote',
  on_site: 'On-site',
  mixed: 'Mixed',
  attendance: 'Attendance',
  engagement: 'Engagement',
  duration: 'Duration',
  weekly_hours: 'Weekly Hours',
  location_req: 'Location Requirement',
  categories: 'Categories',
  description: 'Description',
  rate_client: 'Client Rate',
  anywhere: 'Anywhere',
  us: 'USA',
  us_can_greencard: 'USA / Canada / Greencard',
  experience: 'Experience',
  months_3: '3 months',
  months_6: '6 months',
  months_6_ext: '6 month with possible extension',
  year_1: '1 year',
  year_2: '2 years',
  year_3: '3 years',
  year_4: '4 years',
  year_5: '5 years',
  enabled: 'Enabled',
  disabled: 'Disabled',
  doc_skill_item: 'SKILL_ITEM_',
  doc_other_skill_item: 'OTHER_SKILL_ITEM_',
  doc_exp_position: 'EXPERIENCE_POSITION_',
  doc_exp_from: 'EXPERIENCE_FROM_',
  doc_exp_to: 'EXPERIENCE_TO_',
  doc_exp_company: 'EXPERIENCE_COMPANY_',
  doc_exp_description: 'EXPERIENCE_DESCRIPTION_',
  doc_proj_title: 'PROJECT_TITLE_',
  doc_proj_from: 'PROJECT_FROM_',
  doc_proj_to: 'PROJECT_TO_',
  doc_proj_url: 'PROJECT_URL_',
  doc_proj_description: 'PROJECT_DESCRIPTION_',
  doc_edu_place_name: 'EDUCATION_PLACE_NAME_',
  doc_edu_degree: 'EDUCATION_DEGREE_',
  doc_edu_from: 'EDUCATION_FROM_',
  doc_edu_to: 'EDUCATION_TO_',
  doc_cert_title: 'CERTIFICATE_TITLE_',
  doc_cert_date: 'CERTIFICATE_DATE_',
  doc_lang_item: 'LANGUAGE_ITEM_',
}
